### ISSUE TITLE
Could you plan for typescript supporting?

### ISSUE THREAD

**Issue by NeoLSN** [smirzo/vuex-observable-plugin#16]
Because of lack of '.d.ts'. I can't even do import this module in typescript.
Could you consider a plan for typescript supporting?

**Comment by smirzo** [comment]
Hi @NeoLSN ! Sure, I'll probably end up rewriting the whole module in typescript eventually. Unfortunately, I'm extremely busy atm so to be as frank as possible, this will most likely be at the bottom of my list of priorities for the foreseeable future (since I'm not really a front end dev). Hope that makes sense.

For now however, to get around the issue of importing, you can add a custom declaration to your type declaration file. You might have to restart the server.
```ts
// in your shims-vue.d.ts or any other index.d.ts file

declare module 'vuex-observable-plugin'
``` 
I'll keep the issue open for now, so I'll remember to rewrite the module when I'll finally come round to it.
